import React from 'react'
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
  
export default function layout({children}) {
  return (
    <div>layout for favourite</div>
  )
}
